name: Build

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 이미지 태그
      - name: Set variables
        id: set-variables
        run: |
          git_short_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "Git short hash: $git_short_hash"
          echo "git_short_hash=$git_short_hash" >> $GITHUB_OUTPUT

      # OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::131421611146:role/github_ecs_deploy_role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push image to Amazon ECR
        id: build
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.set-variables.outputs.git_short_hash }}
        with:
          push: true
          context: app
          tags: |
            ${{ env.REGISTRY }}/spendit-receipt-api-dev:${{ env.TAG }}
            ${{ env.REGISTRY }}/spendit-receipt-api-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 배포 트리거
      - name: Trigger to Deploy Receipts API
        if: steps.build.outcome == 'success'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy
          client-payload: '{"tag": "${{ steps.set-variables.outputs.git_short_hash }}"}'